"""initial production schema

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-05-25
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table("user", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sqlmodel.sql.sqltypes.AutoString()), sa.Column("preferred_language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("is_anonymous", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("adminuser", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False, unique=True), sa.Column("hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("chatsession", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id")), sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("chatmessage", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("session_id", sa.Integer(), sa.ForeignKey("chatsession.id")), sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("content", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("citations_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("confidence", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("feedback", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("message_id", sa.Integer(), sa.ForeignKey("chatmessage.id")), sa.Column("helpful", sa.Boolean(), nullable=False), sa.Column("reasons_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("comment", sqlmodel.sql.sqltypes.AutoString()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("sourcedocument", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("source_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("raw_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("status", sa.Enum("pending", "approved", "rejected", name="approvalstatus"), nullable=False), sa.Column("last_crawled_at", sa.DateTime(), nullable=False), sa.Column("published_at", sa.DateTime()), sa.UniqueConstraint("url", name="uq_sourcedocument_url"))
    vector_type = sa.Text()
    op.create_table("document_chunks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.Integer(), sa.ForeignKey("sourcedocument.id"), nullable=False), sa.Column("chunk_index", sa.Integer(), nullable=False), sa.Column("text", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("token_count", sa.Integer(), nullable=False), sa.Column("is_active", sa.Boolean(), nullable=False), sa.Column("embedding_vector", vector_type), sa.Column("embedding_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("embedding_provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("embedding_model", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("embedding_dimension", sa.Integer(), nullable=False), sa.Column("embedding_created_at", sa.DateTime()), sa.Column("created_at", sa.DateTime(), nullable=False), sa.UniqueConstraint("document_id", "chunk_index", name="uq_documentchunk_document_chunk_index"))
    if bind.dialect.name == "postgresql":
        op.execute("ALTER TABLE document_chunks ALTER COLUMN embedding_vector TYPE vector(1024) USING embedding_vector::vector")
    op.create_table("crawljob", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("seed_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("page_limit", sa.Integer(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False), sa.Column("finished_at", sa.DateTime()))
    op.create_table("crawllog", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("job_id", sa.Integer(), sa.ForeignKey("crawljob.id")), sa.Column("url", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("status_code", sa.Integer()), sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("failedquery", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("query", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("routed_office", sqlmodel.sql.sqltypes.AutoString()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("officecontact", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("purpose", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("email", sqlmodel.sql.sqltypes.AutoString()), sa.Column("phone", sqlmodel.sql.sqltypes.AutoString()), sa.Column("location", sqlmodel.sql.sqltypes.AutoString()), sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString()))
    op.create_table("faqentry", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString()), sa.Column("requires_handoff", sa.Boolean(), nullable=False))
    op.create_table("languagesetting", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False, unique=True), sa.Column("native_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("english_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("enabled", sa.Boolean(), nullable=False))
    op.create_table("analyticsevent", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("category", sqlmodel.sql.sqltypes.AutoString()), sa.Column("metadata_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("handoffticket", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_email", sqlmodel.sql.sqltypes.AutoString()), sa.Column("question", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("office_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("checklisttemplate", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("audience", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("items_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_table("noticesummary", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("action_required", sqlmodel.sql.sqltypes.AutoString()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("savedanswer", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("user_id", sa.Integer(), sa.ForeignKey("user.id")), sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("citations_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("notice", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("date", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString()))
    op.create_table("sourceapproval", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("document_id", sa.Integer(), sa.ForeignKey("sourcedocument.id"), nullable=False), sa.Column("status", sa.Enum("pending", "approved", "rejected", name="approvalstatus", create_type=False), nullable=False), sa.Column("reviewer_id", sa.Integer(), sa.ForeignKey("adminuser.id")), sa.Column("notes", sqlmodel.sql.sqltypes.AutoString()), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_table("responsecorrection", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("failed_query_id", sa.Integer(), sa.ForeignKey("failedquery.id")), sa.Column("corrected_answer", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("language", sqlmodel.sql.sqltypes.AutoString(), nullable=False), sa.Column("approved", sa.Boolean(), nullable=False), sa.Column("created_at", sa.DateTime(), nullable=False))
    op.create_index("ix_user_email", "user", ["email"])
    op.create_index("ix_sourcedocument_url", "sourcedocument", ["url"])
    op.create_index("ix_sourcedocument_raw_hash", "sourcedocument", ["raw_hash"])
    op.create_index("ix_languagesetting_code", "languagesetting", ["code"])


def downgrade() -> None:
    for table in ["responsecorrection", "sourceapproval", "notice", "savedanswer", "noticesummary", "checklisttemplate", "handoffticket", "analyticsevent", "languagesetting", "faqentry", "officecontact", "failedquery", "crawllog", "crawljob", "document_chunks", "sourcedocument", "feedback", "chatmessage", "chatsession", "adminuser", "user"]:
        op.drop_table(table)
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("DROP TYPE IF EXISTS approvalstatus")
